### ISSUE TITLE
Update CRDs with schema validation and remove deprecated APIs

### ISSUE THREAD

**Issue by yashmehrotra** [cruise-automation/rbacsync#29]
Hey, I was trying out this project and had to make some changes to remove all the deprecation warnings and get it to working on k8s version 1.20

Changes I made:
- Updated CRDs with OpenAPIV3 schema validation
- Updated CRD API
- Update RoleBindings API

I am not sure whether this project is actively being maintained or not, but if you are interested I can open a PR with the updated manifests.

**Comment by stevvooe** [comment]
I think #31 should cover you, but if you have some fixes, feel free to submit a PR.
