### ISSUE TITLE
Accounts setup documentation

### ISSUE THREAD

**Issue by pesimon** [cruise-automation/rbacsync#5]
Hi, 

Unfortunately I wasn't able to set this up. Since the whole GSuite delegation account and GCP service account and thier permission are quite complex to setup, some screenshots might be helpful. I know it's a very young project but it may raise adoption and people may be willing to maintain documention as well. 

Hence, the linked Fin.com is not accessible outside the US but Google cache has it archived (not sure how long)

https://webcache.googleusercontent.com/search?q=cache:Q5VZUOE3cNgJ:https://www.fin.com/post/2017/10/navigating-google-suite-directory-api+&cd=1&hl=en&ct=clnk&gl=de  

Cheers, 
Peter

**Comment by stevvooe** [comment]
@pesimon Thanks for the report, but without more information, we won't be able to improve on the documentation. I'm going to close this for now. If you have more information in the future on what step went awry, please feel free to comment on this issue or open a new one.
