### ISSUE TITLE
metrics: add gauges for fulfilled configurations 

### ISSUE THREAD

**Issue by stevvooe** [cruise-automation/rbacsync#8]
Need a better way of ascertaining whether RBACSync is healthy. Export metrics for number of fulfilled rbacsyncconfigs vs errored. This will allow detection of upstream issues with monitoring.

**Comment by stevvooe** [comment]
May want to pair this work with https://github.com/cruise-automation/rbacsync/issues/6#issuecomment-455012962 to add status reporting.

**Comment by mattlandis** [comment]
Discussed in further detail with @stevvooe offline.  Documenting more details here for when this gets picked up.

Metrics in the Controller:
* `rbacsync_config_status` *(gauge with labels)* - Gauge counting the number of RBACSyncConfigs and RBACSyncClusterConfigs (type as label) and the status of the processed config.
* `rbacsync_binding_status` *(gauge with labels)* - Gauge counting the number of RoleBindings and ClusterRoleBIndings configured by the controller and their statuses [created/deleted/duplicate/error states]

Metrics in Mapper/GSuite
* `rbacsync_gsuite_client_creation_status` *(counter with labels)* - Counts the status of gsuite client creations
* `rbacsync_gsuite_members_status` *(counter with labels)* - Counts the status of calls to gsuite with labels for state - TimeoutError, NotFoundError, Cancled, UnknownError Success.
* `rbacsync_gsuite_members_latency` *(histogram)* - Histogram of the calls to gsuite for group memberships.

**Comment by mllu** [comment]
this issue was addressed in https://github.com/cruise-automation/rbacsync/pull/19 and released in https://github.com/cruise-automation/rbacsync/releases/tag/v1.2.0, we should be good to close this issue. Thanks for helping review.
